[build]
  # 构建命令
  command = "npm run build"
  
  # 发布目录
  publish = "dist"
  
  # 基础目录
  base = "frontend"
  
  # Node.js 版本
  environment = { NODE_VERSION = "18" }

[build.environment]
  # 设置环境变量
  NODE_ENV = "production"

# 重定向规则 - 支持 React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置 - 缓存优化
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"